### ISSUE TITLE
Node label omission

### ISSUE THREAD

**Issue by gstonge** [andresantoro/Social_Consensus#1]
If you look at the network structure generated by social_consensus_structure.py in the JSON file, some node label can be missing from the sequence of integer expected. For instance, if we want 500 nodes, label 164 might be missing. Are degree zero node removed maybe?

**Comment by gstonge** [comment]
After looking at the code, I think this is what is happening : node zero are not inserted in the dictionary, since we scan over edges. This was desirable, because we want to reach a consensus : however, current implementations of the solver (python/c++) were built upon the supposition that all nodes with label from 0 to network.size() were passed in the JSON file. The python implementation did not throw an error message, contrary to the c++ one, but it is possible that all simulations from the python code are wrong because of this. 

I will modify the c++ code such that the state of nodes (opinion) is encoded in a dictionary also, so we can pass any kind of label, not necessarily an ordered list of ints. Once this is implemented, we can if the simulation results were biased for the python code.

**Comment by gstonge** [comment]
changing plan : it would fuck everything. I will relabel the nodes in the structure code such that we have consecutive integers for the largest component.

**Comment by andresantoro** [comment]
What you say it's true! But in the case of 500 nodes and using an ER structure, depending on the number of links that we choose at the beginning (that also represents the average degree < k >),  we could end up with a network with multiple connected components. Anyway, since in all our simulations we used < k >= 8, we should have only 1 connected component containing all the nodes.

**Comment by gstonge** [comment]
Yep good. Anyway its seems to work correctly with the node relabeling. Its good to keep in mind we should not use a too low average degree, otherwise the size of the network can get significantly affected. We can close this issue.
